version: 0.0
os: linux

files:
  - source: /dist
    destination: /var/www/html

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root